import { SemanticCluster } from "@/lib/admin/types";

export const DEFAULT_SEMANTIC_CLUSTERS: SemanticCluster[] = [
  {
    id: "smartphones",
    category: "Смартфоны и гаджеты",
    slug: "smartphones",
    h1Title: "Сравнение цен на смартфоны и мобильные телефоны",
    metaDescription: "Сравните цены на популярные смартфоны Apple iPhone, Samsung Galaxy, Xiaomi, Realme и HONOR на Wildberries и Ozon с алгоритмом Анти-Фейк.",
    keywords: ["смартфоны", "купить смартфон", "iphone 16", "samsung galaxy", "xiaomi", "цена смартфонов", "ozon", "wildberries"],
    popularQueries: [
      { query: "iPhone 16 Pro Max", anchorText: "Сравнить цены на Apple iPhone 16 Pro Max", priority: 1.0, tags: ["Apple", "Флагманы"] },
      { query: "Samsung Galaxy S24 Ultra", anchorText: "Купить Samsung Galaxy S24 Ultra со скидкой", priority: 0.95, tags: ["Samsung", "Android"] },
      { query: "Xiaomi 14 Ultra", anchorText: "Сравнить предложения Xiaomi 14 Ultra", priority: 0.9, tags: ["Xiaomi", "Камерофон"] },
      { query: "POCO X6 Pro 5G", anchorText: "Купить недорого POCO X6 Pro 5G", priority: 0.85, tags: ["POCO", "Бюджетный"] },
      { query: "Смартфон Realme 12 Pro+", anchorText: "Цены на Realme 12 Pro+ на маркетплейсах", priority: 0.8, tags: ["Realme"] },
    ],
  },
  {
    id: "laptops",
    category: "Ноутбуки и компьютеры",
    slug: "laptops",
    h1Title: "Цены на ноутбуки для работы, учебы и игр",
    metaDescription: "Выбирайте ноутбуки Apple MacBook, ASUS ROG, Lenovo Legion, MSI и Huawei на WB и Ozon с проверкой оригинальности и гарантией честной цены.",
    keywords: ["ноутбуки", "купить ноутбук", "macbook air m3", "игровой ноутбук", "asus rog", "lenovo legion", "сравнение цен"],
    popularQueries: [
      { query: "Apple MacBook Air 13 M3", anchorText: "Цены на MacBook Air 13 M3 на WB и Ozon", priority: 0.98, tags: ["Apple", "Ультрабуки"] },
      { query: "Apple MacBook Pro 14 M3 Pro", anchorText: "Купить MacBook Pro 14 M3 Pro выгодно", priority: 0.95, tags: ["Apple", "Pro"] },
      { query: "Игровой ноутбук ASUS ROG Strix", anchorText: "Сравнить цены на ASUS ROG Strix", priority: 0.9, tags: ["ASUS", "Гейминг"] },
      { query: "Lenovo Legion 5 Pro RTX 4070", anchorText: "Предложения на Lenovo Legion 5 Pro", priority: 0.88, tags: ["Lenovo", "RTX 4070"] },
      { query: "Huawei MateBook D 16", anchorText: "Ноутбук для офиса Huawei MateBook D 16", priority: 0.82, tags: ["Huawei", "Офис"] },
    ],
  },
  {
    id: "audio",
    category: "Наушники и аудиотехника",
    slug: "audio",
    h1Title: "Беспроводные наушники и портативная акустика",
    metaDescription: "Сравнение цен на оригинальные AirPods Pro, Sony WH-1000XM5, Marshall Major и беспроводные колонки JBL на Wildberries и Ozon.",
    keywords: ["наушники", "airpods pro 2", "sony wh-1000xm5", "marshall major iv", "беспроводные наушники", "jbl колонка"],
    popularQueries: [
      { query: "Apple AirPods Pro 2 Type-C", anchorText: "Купить оригинальные AirPods Pro 2 с Type-C", priority: 0.96, tags: ["AirPods", "ANC"] },
      { query: "Sony WH-1000XM5", anchorText: "Цены на наушники Sony WH-1000XM5", priority: 0.92, tags: ["Sony", "Шумоподавление"] },
      { query: "Marshall Major IV", anchorText: "Сравнить стоимость Marshall Major IV", priority: 0.88, tags: ["Marshall", "Ретро"] },
      { query: "JBL Charge 5", anchorText: "Портативная колонка JBL Charge 5 со скидкой", priority: 0.85, tags: ["JBL", "Акустика"] },
      { query: "Samsung Galaxy Buds2 Pro", anchorText: "Купить Galaxy Buds2 Pro со скидкой", priority: 0.8, tags: ["Samsung"] },
    ],
  },
  {
    id: "appliances",
    category: "Бытовая техника и умный дом",
    slug: "appliances",
    h1Title: "Техника для дома и кухни по выгодным ценам",
    metaDescription: "Роботы-пылесосы Dreame и Roborock, кофемашины DeLonghi, аэрогрили и фены Dyson со сравнением реальных скидок и защитой от подделок.",
    keywords: ["робот пылесос", "dreame l20 ultra", "roborock s8", "кофемашина delonghi", "фен dyson supersonic", "бытовая техника"],
    popularQueries: [
      { query: "Робот-пылесос Roborock S8 Pro Ultra", anchorText: "Сравнить цены на Roborock S8 Pro Ultra", priority: 0.95, tags: ["Roborock", "Роботы"] },
      { query: "Робот-пылесос Dreame L30 Ultra", anchorText: "Выгодные предложения на Dreame L30 Ultra", priority: 0.9, tags: ["Dreame", "Влажная уборка"] },
      { query: "Кофемашина DeLonghi Magnifica S", anchorText: "Купить кофемашину DeLonghi Magnifica S", priority: 0.88, tags: ["DeLonghi", "Кофе"] },
      { query: "Фен Dyson Supersonic HD08", anchorText: "Оригинальный фен Dyson Supersonic со скидкой", priority: 0.93, tags: ["Dyson", "Уход"] },
      { query: "Аэрогриль Xiaomi Smart Air Fryer", anchorText: "Цены на аэрогриль Xiaomi Smart Air Fryer", priority: 0.82, tags: ["Xiaomi", "Кухня"] },
    ],
  },
  {
    id: "wearables",
    category: "Смарт-часы и браслеты",
    slug: "wearables",
    h1Title: "Умные часы и фитнес-трекеры",
    metaDescription: "Сравнение цен на Apple Watch Series 9 и Ultra 2, Samsung Galaxy Watch, Garmin Fenix и Xiaomi Smart Band.",
    keywords: ["смарт часы", "apple watch ultra 2", "garmin fenix", "galaxy watch 6", "фитнес браслет"],
    popularQueries: [
      { query: "Apple Watch Series 9 45mm", anchorText: "Цены на Apple Watch Series 9 на маркетплейсах", priority: 0.94, tags: ["Apple Watch"] },
      { query: "Apple Watch Ultra 2", anchorText: "Купить смарт-часы Apple Watch Ultra 2", priority: 0.92, tags: ["Ultra", "Спорт"] },
      { query: "Garmin Fenix 7 Pro", anchorText: "Спортивные часы Garmin Fenix 7 Pro", priority: 0.89, tags: ["Garmin", "Экстрим"] },
      { query: "Samsung Galaxy Watch 6 Classic", anchorText: "Galaxy Watch 6 Classic со скидкой", priority: 0.85, tags: ["Samsung"] },
      { query: "Xiaomi Smart Band 8 Pro", anchorText: "Фитнес-браслет Xiaomi Band 8 Pro", priority: 0.8, tags: ["Фитнес"] },
    ],
  },
  {
    id: "auto",
    category: "Автотовары и электроника",
    slug: "auto",
    h1Title: "Видеорегистраторы, автосканеры и компрессоры",
    metaDescription: "Поиск и сравнение цен на автомобильные видеорегистраторы 70mai, пусковые устройства, пылесосы и компрессоры на WB и Ozon.",
    keywords: ["видеорегистратор", "70mai dash cam", "пусковое устройство", "автокомпрессор", "автотовары"],
    popularQueries: [
      { query: "Видеорегистратор 70mai Dash Cam 4K A810", anchorText: "Сравнить 70mai Dash Cam 4K A810 на WB и Ozon", priority: 0.9, tags: ["70mai", "4K"] },
      { query: "Пуско-зарядное устройство Baseus Super Energy", anchorText: "Купить пусковое устройство Baseus Super Energy", priority: 0.85, tags: ["Baseus", "Джамп-стартер"] },
      { query: "Автомобильный компрессор Xiaomi 70mai", anchorText: "Цены на компрессор Xiaomi 70mai", priority: 0.82, tags: ["Xiaomi", "Компрессоры"] },
    ],
  },
];
