name: Deploy Next.js to Yandex Cloud

on:
  push:
    branches:
      - main  # Если ветка master, замените main на master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_KEY }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="cr.yandex/${{ vars.YC_REGISTRY_ID }}/nextjs-app:latest"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy Revision via CLI
        run: |
          # 1. Скачиваем бинарник YC напрямую с зеркала хранилища (оно доступно из Гитхаба)
          curl -sSL https://yandexcloud.net | bash -s -- -i ./yandex-cloud -n
          
          # 2. Записываем ключ авторизации
          echo '${{ secrets.YC_SA_KEY }}' > key.json
          
          # 3. Настраиваем и деплоим
          ./yandex-cloud/bin/yc config profile create sa-profile
          ./yandex-cloud/bin/yc config set service-account-key key.json
          ./yandex-cloud/bin/yc config set folder-id ${{ vars.YC_FOLDER_ID }}
          
          ./yandex-cloud/bin/yc serverless container revisions deploy \
            --container-name 'wobuy-site' \
            --image cr.yandex/${{ vars.YC_REGISTRY_ID }}/nextjs-app:latest \
            --cores 1 \
            --memory 256MB \
            --concurrency 10 \
            --execution-timeout 30s \
            --service-account-id 'aje9stbod1kgprfq6e4k'
