name: Deploy Next.js to Yandex Cloud

on:
  push:
    branches:
      - main  # Если ветка master, замените main на master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_KEY }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="cr.yandex/${{ vars.YC_REGISTRY_ID }}/nextjs-app:latest"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Extract Service Account ID
        id: sa_id
        run: |
          echo '${{ secrets.YC_SA_KEY }}' > key.json
          ID=$(grep -o '"service_account_id": "[^"]*' key.json | grep -o '[^"]*$')
          echo "id=$ID" >> $GITHUB_OUTPUT

      - name: Deploy to Yandex Serverless Container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_KEY }}
          container-name: 'wobuy-site'
          folder-id: ${{ vars.YC_FOLDER_ID }}
          revision-image-url: cr.yandex/${{ vars.YC_REGISTRY_ID }}/nextjs-app:latest
          revision-cores: 1
          revision-memory: 256MB
          revision-concurrency: 10
          revision-execution-timeout: 30s
          revision-service-account-id: ${{ steps.sa_id.outputs.id }}
